/*
 * generated by Xtext
 */
package anl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AnimationsLanguageUiModule extends anl.ui.AbstractAnimationsLanguageUiModule {
	public AnimationsLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
