/*
* generated by Xtext
*/
package anl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class AnimationsLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
