/*
 * generated by Xtext
 */
package anl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import anl.ui.internal.AnimationsLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AnimationsLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AnimationsLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AnimationsLanguageActivator.getInstance().getInjector(AnimationsLanguageActivator.ANL_ANIMATIONSLANGUAGE);
	}
	
}
