/*
* generated by Xtext
*/
package anl.ui.contentassist;

import anl.ui.contentassist.AbstractAnimationsLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AnimationsLanguageProposalProvider extends AbstractAnimationsLanguageProposalProvider {

}
