/*
 * generated by Xtext
 */
package anl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AnimationsLanguageRuntimeModule extends anl.AbstractAnimationsLanguageRuntimeModule {

}
